#!/usr/bin/env bash
# Produces dist/nf-inject-bundled.js — a single self-contained script that
# embeds both jars (base64) and self-extracts them on load, so a user only has
# to drop ONE file in their scripts/ folder.
#
# NOTE: the bundle only helps the *runtime-attach* path (JDK runtime, e.g.
# GraalVM): on load it writes the jars to a cache dir and points Inject.agentJar
# there, then attaches when you first inject. The -javaagent path is unaffected
# (that flag needs the jar on disk at JVM launch, before any script runs), so
# -javaagent users still ship dist/nf-inject-agent.jar + dist/nf-holder.jar.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; cd "$here"

AGENT="dist/nf-inject-agent.jar"; HOLDER="dist/nf-holder.jar"
[ -f "$AGENT" ] && [ -f "$HOLDER" ] || { echo "FAIL: run ./build.sh first ($AGENT / $HOLDER missing)" >&2; exit 1; }

AGENT_B64="$(base64 -w0 "$AGENT")"
HOLDER_B64="$(base64 -w0 "$HOLDER")"
OUT="dist/nf-inject-bundled.js"

{
  cat <<'PROLOGUE'
// nf-inject-bundled.js — GENERATED by make-bundle.sh. Do not edit by hand.
//
// Single-file build of lb-inject: the agent + holder jars are embedded below as
// base64 and self-extracted to a cache dir on load. Drop just THIS file in your
// scripts/ folder and `load()` it; it defines globalThis.Inject like nf-inject.js.
//
//   load("/abs/path/nf-inject-bundled.js");
//   var h = Inject.inject("net.minecraft.client.Minecraft","getFps","HEAD", fn);
//
// Self-extraction enables the runtime-attach path (JDK runtime). For the
// -javaagent path you still need the jar on disk at JVM launch (see README).

(function () {
    var System_ = Java.type("java.lang.System");
    var Files = Java.type("java.nio.file.Files");
    var Paths = Java.type("java.nio.file.Paths");
    var Base64 = Java.type("java.util.Base64");
PROLOGUE

  printf '    var AGENT_B64 = "%s";\n' "$AGENT_B64"
  printf '    var HOLDER_B64 = "%s";\n' "$HOLDER_B64"

  cat <<'EXTRACT'
    try {
        var dir = Paths.get("" + System_.getProperty("java.io.tmpdir"), "nf-inject");
        Files.createDirectories(dir);
        var agentJar = dir.resolve("nf-inject-agent.jar");
        var holderJar = dir.resolve("nf-holder.jar");   // name fixed: agent's Boot-Class-Path resolves it next to itself
        Files.write(agentJar, Base64.getDecoder().decode(AGENT_B64));
        Files.write(holderJar, Base64.getDecoder().decode(HOLDER_B64));
        globalThis.__NF_BUNDLED_AGENT_JAR = "" + agentJar.toAbsolutePath();
    } catch (e) {
        throw new Error("nf-inject-bundled: could not extract embedded jars: " + e);
    }
})();

EXTRACT

  # the library itself, verbatim
  cat nf-inject.js

  cat <<'EPILOGUE'

// Point the freshly-defined Inject at the self-extracted agent jar.
(function () {
    if (typeof globalThis.Inject !== "undefined" && globalThis.__NF_BUNDLED_AGENT_JAR) {
        globalThis.Inject.agentJar = globalThis.__NF_BUNDLED_AGENT_JAR;
    }
})();
EPILOGUE
} > "$OUT"

echo "built $OUT ($(du -h "$OUT" | cut -f1); agent $(du -h "$AGENT"|cut -f1) + holder $(du -h "$HOLDER"|cut -f1) embedded)"
